services:
  - type: web
    name: ai-agent-phase2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: MAX_UPLOAD_MB
        value: "10"
      - key: MAX_ROWS_IN_FIRESTORE
        value: "500"
      - key: MAX_ROWS_IN_PROMPT
        value: "50"
